version: "3.9"
services:

  auth_db:
    image: postgres
    container_name: auth_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_auth
      - PGDATA=/var/lib/postgresql/cd_auth
    volumes:
      - ./db/shortcut/cd_auth:/var/lib/postgresql/cd_auth
    restart: always
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "9900:9900"
    environment:
      - SECURITY_OAUTH2_RESOURCE_USERINFOURI=http://auth:9000/user
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth_db:5432/cd_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_NOTIFICATION=http://notification:9920
    container_name: auth
    depends_on:
      - auth_db

  desc_db:
    image: postgres
    container_name: desc_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_desc
      - PGDATA=/var/lib/postgresql/cd_desc
    volumes:
      - ./db/shortcut/cd_desc:/var/lib/postgresql/cd_desc
    restart: always
  desc:
    build:
      context: ./services/desc
      dockerfile: Dockerfile
    ports:
      - "9902:9902"
    environment:
      - SECURITY_OAUTH2_RESOURCE_USERINFOURI=http://auth:9000/user
      - SPRING_DATASOURCE_URL=jdbc:postgresql://desc_db:5432/cd_desc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_NOTIFICATION=http://notification:9920
    container_name: desc
    depends_on:
      - desc_db

  mock_db:
    image: postgres
    container_name: mock_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mock
      - PGDATA=/var/lib/postgresql/mock
    volumes:
      - ./db/shortcut/mock:/var/lib/postgresql/mock
    restart: always
  mock:
    build:
      context: ./services/mock
      dockerfile: Dockerfile
    ports:
      - "9912:9912"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mock_db:5432/mock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SECURITY_OAUTH2_RESOURCE_USERINFOURI=http://auth:9000/user
      - SERVER_NOTIFICATION=http://notification:9920
    container_name: mock
    depends_on:
      - mock_db

  notification_db:
    image: postgres
    container_name: notification_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_notification
      - PGDATA=/var/lib/postgresql/cd_notification
    volumes:
      - ./db/shortcut/cd_notification:/var/lib/postgresql/cd_notification
    restart: always
  notification:
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    ports:
      - "9920:9920"
    environment:
      - SECURITY_OAUTH2_RESOURCE_USERINFOURI=http://auth:9000/user
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification_db:5432/cd_notification
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SERVER_AUTH=http://auth:9900
      - SERVER_SITE_URL_LOGIN=http://site:8081/login
    container_name: notification
    depends_on:
      - notification_db

  site:
    container_name: site
    build:
      context: ./services/site
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SECURITY_OAUTH2_RESOURCE_USERINFOURI=http://auth:9000/user
      - SECURITY_OAUTH2_TOKENURI=http://auth:9900/oauth/token
      - SERVER_AUTH=http://auth:9900
      - SERVER_AUTH_PING=http://auth:9900/ping
      - SERVICE_MOCK=http://mock:9912
    depends_on:
      - auth
      - desc
      - mock
      - notification
